apiVersion: v1
kind: Pod
metadata:
  name: nvidia
spec:
  runtimeClassName: nvidia-rtx2080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu
            operator: In
            values:
            - rtx-2080
