apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: kube-system
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/name: traefik-forward-auth
data:
  INSECURE_COOKIE: 'false'
  COOKIE_DOMAIN: saldivar.io
  DOMAINS: saldivar.io
  AUTH_HOST: auth.saldivar.io
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://keycloak.saldivar.io/realms/inferno
