apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
  labels:
    app.kubernetes.io/component: helm-release
    app.kubernetes.io/name: cloudnative-pg
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system
      version: ">=0.20.0 <1.0.0"
  values:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - minas-tirith-vm
                  - minas-tirith
                  - pelargir-vm
                  - pelargir
