---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBEOECMCp6XZ23QMnDkMBBFa7K9131GTKxac/EeXISCJEvf6a8WVzAMrnlruld9617Ujum30qspJ3/Lv8ZskU59tVrPMF9R5jozc3kGPbXshcwL/xC7WFIVS+0+8t9aV4KwGY/rLMgdrXl6IOZZhNiEJbPQvCi6YCe/RU+55U+y5rDZBcyNBnpp7QBByQDtXf/md1g+3y+kfzpWHq0PtdnMBpv0eipGbOZX/jTmg9RKsRgCBG3Q+pOttW8XqmCanzN4qGIZktV4HYkcbfE9kVxHsUNLU14fJf3x/3iUd1Pi0F5OscuvdN3CyRCF/lX3FqyhF/O5wZhz3RI/UmVZogK+iyJPQVW0KldtUqwPnwkD+dK8Uwk31MUGXoL35bYv7iZsC4sy2FgzJNqiHG1obkYMrTDA/IZ6MmkOghhdIfsa+HjN97QQYp/LhPqAH+Sv7a9C+qYZXlhjGG2RdZwLVt3a+/B23svxt1cTEEt8EfeW4987WVJYrs4cSnMQHMx+MYFDCbzijihbPTaKHuUqHcGcTqQEQlpNPhxmyuJYeB5UPMK+HBKugoO7QN7qxZrnwxKvW3NE35phK039Mc3dS0PwFbv64QQvXfPvoeG4/yxlpoqwzA3WmgxyO0P80ApDltRpqi6PbGlGnvqXT2gbfsbtqQM1l/J8H2HbnLJDwAwRxkTxhDCFLm5/BfOH6U2Wo66IJttXWVqYH42BaoS6ZZi80z/gKiI+3wg0NaplAmkogyrDIc7o//SZ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
