---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homeassistant
  namespace: homeassistant
spec:
  encryptedData:
    secrets.yaml: AgA/Vd1pC1IkcvKbt7Y0A47OpOPScpWx0f81QybIH7V4p0Esvdg3DKW51o116AJmSozTPlA1/lifZQIPBgzxvnHYvyWoxVIvgg2LbbO/uqkeWxpWTM7oTiDNChB6oH10s9/ooC8UfEGJNzuQI1oWwpw5qReT7yegz7Mc/czQ3AtbandPRl1xZDO1MhXADdA55TNV5hrJiiVw2UUizfa7oR4sAJ8ssquKBTWUk15zgzOsN1kLLN1C5DDiqu7rd1lVcS5vfXA8XtjgSVF/BrbQl2HBIUQkTfNN9iGHaQDE3x13wJED1y/xcvT4eCdG7xyFB+NPJErwJDcyRgfP4L/0L3lHZaBVhkINuLyueFAugi1QUBIkCeqZpknmFIDfd4Jy4O7Z0npqpsufmKAS/d1udCwS/wCoCrQoRlZwoHsAaIqGcTA8ZI2ztC7aiK2/E5L8ogNWc0C6KIh+G3BZESxMwSLnyNvdtLyyby3hdq26jmSZEGBZVyzw2vG36YT9upmy4nTJovyzLNZaa2bh5lftIXsjYJwas70Iv2SwepLZlhoMi5cMXTZgkK47XptQ6fZG5Fz3a0fAXRc9BVGoolZebZW0UfjWnPK0kO6YtFfpyMyzKvFPOBCBMv1DYrgW43zJMfCSKGUGSxU3+YatX1azNIgIitC7PJxNXq89agIsQTC/+bX+7P7gWIS2AyLd0SM9WMjdfbYSvcDky6n1PmyNQEG5Y0bRSyNG
  template:
    metadata:
      creationTimestamp: null
      name: homeassistant
      namespace: homeassistant
    type: Opaque
