---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    DOMAIN: AgA26CRbHZ8ATdXVwfyplZjEdv/e9SVeCDtHUXanJmAZUjAGRt4uW3ng8+nVsvIjFvIL+PL7CbMI+xfG3HiW/Q9qKc49uy5dsN5xTK1VWcxSpiQqUYvy3UKB0LWVTC0koYasn7qnAebfldz3TJd5Kt8NPeh08falPSLIVRrIftblBKD8GtiG5O63u6pW9m3MJqrm6Q/rB8gvgh9dkB9CYs+WbERvcSAW+SxNTaI9/VMtnHHOnWoCFpM/XqBVmRlw4jMK/F0jRAySiwN/aL+h4BAG+hpCC2isU9U8XIHrYuj7Y5Kkj4y995x+cTapxvOe4ZxRkd1XmD3sIC/k1Nw7N6dc/fvYVaTFKcNHxbD7EzxsovvjEmg60fScnQvvLmvUtsJ66uKEGzuW7FZkWNIqjTQ/6KBtEIog0Qef2S53QAMVBPYTY/LZ6xNp26RUqxxru25kwwQEgL5VKi7NlMRqW8supP+BNeIc5CJxnnXfbRIiDwLw4FdyICJyiRc4ZIeBVUwxs1t/NagDq/i5CdijoC1X5Xhw3/f+EZkBfQSSbIhKJvnp3K9Dfc9aHmdCUMpB0p/DEN2jyf/thCK8tPHFiFPJaV9gLsmZfCpP5BSSQKq97hn1UppL1pP42Dn8UbrOAozHZYsafTvEPirrcqouVkQMGIGf1V5P/OjCjy/WWaMtjrzMEWT3F86vyyqrqypmi63zERsB0Zddkr3y1TrgYSPmui+DgQ==
    KC_ADMN: AgBCL3ywGsP7nOhLdc53maoMxjXe0DnsLpk188IEMkqkpJs/V7dKAqmezr4aRtrtopk54x0YC1U6sIlbF9KtbVBlUQC5Fbw6xB59lCNywTScdo3O00me7Fm/qScAKBE7ZzVFtU//nzoiXUfaoLMQsp9NPuncdTaNZ+IP9Yx6Y7h13XmswWKG8/e2luRFe5VcOm7GnznsvWodr0HAjmzRi21Jcu6dUy5w2vkJepnWrtqoSp2Ohr57/luX7i4uObvJGQUWqAxnBetUO3L6iv97v/uOFO3kZ7z1iVWHucO2W3vu+xSixIcOlPUbg+wxcQenIRN4T9GiumulpsVN8fL8QTxFxWerOUtmuPLejCXt7bnLLEs4RcNbDrTe67aq72ufg8vIVW0qQqkulizReWLn+ULXKjPJ5CcPKh64pNZgHty4cc/Mxr1DldxNLBhlw+EK14rvn5ns4XUPcMOI/9Ra0Yj1LmiLM2aAtF/cI8jHMRjR+/6Mhs+UynLpFxMplLO5nErcINPmjULmUtlFO4ftOCE8FG3Eheom4hv4VVl0dyaM5JBEt1p2R5eshdfEVmqCRQHrvvBmSHJi4UlsA4pwFMvE03L0OFMAE+rYa2TaUZDj8fX1BU1ZHKVAtHEvZo10IxrXlYAEuxjwwG7Nt/YItzDE/qucWzZA3dEmWpCQo/9NkOKwL10WiMcuwOgMVQJ0hakIUXhQlA==
    KC_PASS: AgAnE1e94URrK8OZ9yQ7Dv11p1wBZO7UQW7nbG+X+QZ7reB5mgErXrdXSwkjfgDbh4OWeOnz/0Ta1onmMdIIBrjXzW7C9Sc4BZwQ5AJQAo1P24hnXYE5fJ8Sdk4bDKZN4eXb8mB5ur3nlz2GHViDBgMatFMLwmKUQCLIZ9WTfCJEo/a7Mh8D7lybmVeI12woXKYTEYfmfe8HIjtGNgcLTweTmrpJZh2LLP4aomjURrlw2LkTX8Ty/N65Bs2oOK888flxO8dEuIDcWPmbUpRu+nPDDj3WKfcZFdXiVd8usdWgbhyXsCt3A6GW8VwpV+UPGSz18o/UaETGIpQzrF/soMBNm9YxymB9jSDPuL/uKCBbzVxYKzWRLULe7z6SOAmTktZBQ4tEh7omCcdtnoCFG7gUJJKihmURQVivvPYIbnY4DmBIC47JmUX/HnQt2rm45U2z3XPkx0GwAe63SnSIgSwzZHsKkfSGnTJM1VPHsT1K7thoB0r26euHu+5TIdYT0f8i+Y2OUZX0ayO8v7k84PdWVPwSxvDFi0ofez4JuR9OsEBmdgDnChFqfB1xpbfLTwoaVDWLmI2v4RU/wx11iK0mgwWCH0RPO7ulYHA6lBTI1vzHpURNllZ8uaqsUAK4VOCO8uFvHXZHcZ/h53xWMYrXhqOxGlnENzlKNecsnmqJrcjIgfBLYenLUQ1h0EPMgbadDUhAjD4SUBLakIsOUhZU8C7TPzxpCmM8uA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: secrets
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/part-of: keycloak
      name: keycloak
      namespace: keycloak
    type: Opaque
